spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test_activity?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
        #99服务器连evidence2_3_dev_test(本地可以连，但是不能在里面执行脚本!)
        username: ddcai
        #本地开发连接evidence2_3_dev
        #   username :  evidence2_3_dev
        password: iflytek
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver

        #连接池的配置信息
        initialSize: 5
        minIdle: 5
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        filters: stat,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
