spring:
     #数据库访问配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_activity?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    #99服务器连evidence2_3_dev_test(本地可以连，但是不能在里面执行脚本!)
    username: ddcai
    #本地开发连接evidence2_3_dev
    #   username :  evidence2_3_dev
    password: iflytek
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver

    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    filters: stat,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

devtools:
  restart:
    enabled: true
  estart:
    additional-paths: src/main/java
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://lvbaiqin.com:8400/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true

################公共属性################

  #pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8800
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath*:com/ddcai/wx/mapper/*.xml
#mybatis.configuration.cache-enabled: true
logging:
  level:
    com.iflytek.evidence.mapper: DEBUG
typeAliasesPackage: com.ddcai.wx.model
fresh: 12
